export const TEAMS = [
  { name: 'Alpha' },
  { name: 'Beta' },
]

export const PLAYERS = [
  { first_name: 'Adam', last_name: 'Broomhead' },
  { first_name: 'Ady', last_name: 'LeRoux' },
  { first_name: 'Brandon', last_name: 'Austin' },
  { first_name: 'Bryan', last_name: 'Bennet' },
  { first_name: 'Cam', last_name: 'Miskin' },
  { first_name: 'Diccon', last_name: 'Mayfield' },
  { first_name: 'Dom', last_name: 'Obrien' },
  { first_name: 'Dom', last_name: 'Andre' },
  { first_name: 'Grahame', last_name: 'Johnston' },
  { first_name: 'Ian', last_name: 'Dyckhoff' },
  { first_name: 'Iggy', last_name: 'Harris' },
  { first_name: 'Jonathan', last_name: 'Midgely' },
  { first_name: 'Pedro', last_name: 'Leon' },
  { first_name: 'Ricky', last_name: 'Iles' },
  { first_name: 'Seb', last_name: 'Mayfield' },
  { first_name: 'Simon', last_name: 'None' },
  { first_name: 'Marc', last_name: 'Sparrow' },
]

export const ROUNDS = [
  {
    number: 1,
    name: 'How Well Do You Know Diccon?',
    emoji: '🧠',
    scheduled_time: '12:00',
    format: 'Quiz — 1 point per correct answer, 10 questions total',
    scoring_guidance: 'Enter the number of correct answers for each team (0–10)',
    max_team_points: 10,
    has_individual_scoring: false,
    has_sub_matches: false,
    sub_match_count: null,
    points_per_win: 1,
    points_per_loss: 0,
  },
  {
    number: 2,
    name: 'Petanque',
    emoji: '🎯',
    scheduled_time: '12:30',
    format: 'Best of 3 — 3v3 team matchup',
    scoring_guidance: 'Record win/loss for each of the 3 sub-matches; individual player results optional',
    max_team_points: 9,
    has_individual_scoring: true,
    has_sub_matches: true,
    sub_match_count: 3,
    points_per_win: 3,
    points_per_loss: 1,
  },
  {
    number: 3,
    name: 'Water Balloon Toss',
    emoji: '💦',
    scheduled_time: '13:00',
    format: 'Last pair standing wins',
    scoring_guidance: 'Enter the winning team; no sub-matches',
    max_team_points: 3,
    has_individual_scoring: false,
    has_sub_matches: false,
    sub_match_count: null,
    points_per_win: 3,
    points_per_loss: 1,
  },
  {
    number: 4,
    name: 'Beer Pong',
    emoji: '🍺',
    scheduled_time: '13:30',
    format: 'Best of 3 — doubles matchup',
    scoring_guidance: 'Record win/loss for each of the 3 sub-matches; individual player results optional',
    max_team_points: 9,
    has_individual_scoring: true,
    has_sub_matches: true,
    sub_match_count: 3,
    points_per_win: 3,
    points_per_loss: 1,
  },
  {
    number: 5,
    name: 'Tennis',
    emoji: '🎾',
    scheduled_time: '14:30',
    format: 'Best of 3 — doubles, first to 11 points per set',
    scoring_guidance: 'Record win/loss for each of the 3 sub-matches; individual player results optional',
    max_team_points: 9,
    has_individual_scoring: true,
    has_sub_matches: true,
    sub_match_count: 3,
    points_per_win: 3,
    points_per_loss: 1,
  },
  {
    number: 6,
    name: 'Taskmaster: Portrait of the Groom',
    emoji: '🎨',
    scheduled_time: '15:30',
    format: '10-minute challenge using found materials; Diccon judges the best portrait',
    scoring_guidance: 'Enter Diccon\'s ranking: winning team gets 5 pts, losing team gets 2 pts',
    max_team_points: 5,
    has_individual_scoring: false,
    has_sub_matches: false,
    sub_match_count: null,
    points_per_win: 5,
    points_per_loss: 2,
  },
  {
    number: 7,
    name: 'Dizzy Bat Relay',
    emoji: '🌀',
    scheduled_time: '16:00',
    format: 'Full team relay — each player does 10 spins before passing the bat',
    scoring_guidance: 'Enter the winning team; no sub-matches',
    max_team_points: 3,
    has_individual_scoring: false,
    has_sub_matches: false,
    sub_match_count: null,
    points_per_win: 3,
    points_per_loss: 1,
  },
  {
    number: 8,
    name: 'Flip Cup Finale',
    emoji: '🏁',
    scheduled_time: '16:30',
    format: 'Full team relay — best of 3',
    scoring_guidance: 'Record win/loss for each of the 3 sub-matches',
    max_team_points: 5,
    has_individual_scoring: false,
    has_sub_matches: false,
    sub_match_count: null,
    points_per_win: 5,
    points_per_loss: 2,
  },
]

export const FORFEITS = [
  'Down your drink',
  'Do 10 press-ups',
  'Speak in a French accent for the next round',
  'Swap a clothing item with the person to your left',
  'Do your best impression of Diccon',
  'Sing the chorus of a song chosen by the other team',
  'Let the other team draw something on your face',
  'Take a selfie with a stranger and post it to the group',
  'Do a lap of the castle in your pants',
  'Drink a mystery cocktail made by the other team',
  'Stand on one leg for the entirety of the next round',
  'Call your mum and tell her you love her on speakerphone',
  'Dance for 30 seconds with no music — the other team picks the style',
  'Eat a spoonful of mustard',
  'Let someone in the group send a message from your phone',
]
